name: deploy
on:
  push:
    branches: [ main, "release/*" ]
    paths-ignore: [ '**.md' ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn
      - name: Build
        run: yarn run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build